export const LOAD_REQUEST_SYMBOLS = "LOAD_REQUEST_SYMBOLS";
export const SET_SUCCESS_SYMBOLS = "SET_SUCCESS_SYMBOLS";
export const SET_ERROR_SYMBOLS = "SET_ERROR_SYMBOLS";
export const SET_SELECTED_SYMBOL = "SET_SELECTED_SYMBOL";
