export const LOAD_REQUEST_LATEST = "LOAD_REQUEST_LATEST";
export const SET_SUCCESS_LATEST = "SET_SUCCESS_LATEST";
export const SET_ERROR_LATEST = "SET_ERROR_LATEST";
/* ****************************************************** */
export const LOAD_REQUEST_LATEST_BASE = "LOAD_REQUEST_LATEST_BASE";
export const SET_SUCCESS_LATEST_BASE = "SET_SUCCESS_LATEST_BASE";
export const SET_ERROR_LATEST_BASE = "SET_ERROR_LATEST_BASE";
/* ****************************************************** */
export const LOAD_REQUEST_LATEST_BASE_SYMBOLS =
	"LOAD_REQUEST_LATEST_BASE_SYMBOLS";
export const SET_SUCCESS_LATEST_BASE_SYMBOLS =
	"SET_SUCCESS_LATEST_BASE_SYMBOLS";
export const SET_ERROR_LATEST_BASE_SYMBOLS = "SET_ERROR_LATEST_BASE_SYMBOLS";
